FROM skeleton

# copy test files
COPY test /dist/test


# Override the NODE_ENV environment variable to 'dev', in order to get required test packages
ENV NODE_ENV dev

# 1. Get test packages; AND
# 2. Install our test framework - mocha
RUN npm update

# Run unit tests
CMD ["npm", "test"]
